name: Building TWRP..

on:
  watch:
    types: [started]
  
env:
  USER: Headache01
  EMAIL: ismailduyan00@gmail.com
  TREE: https://github.com/Headache01/GM8_sprout_shrp.git 
jobs:
  build:
    runs-on: ubuntu-16.04


    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git wget
            sudo apt install python3
            sudo apt install python3-pip
            sudo apt install python
            sudo apt install python-pip

       - name: Download Requirements
         run: |
              cd
              mkdir ~/bin
              PATH=~/bin:$PATH
              export PATH=~/bin:$PATH
              curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
              chmod a+x ~/bin/repo
              ls
              echo "PATH=~/bin:$PATH" >> .bashrc
              source ~/.bashrc
              sudo apt-get install repo -y
              sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev


       - name: Get SHRP Sources
         run: |
              mkdir /home/runner/work/recovery-builder/recovery-builder/shrp
              cd /home/runner/work/recovery-builder/recovery-builder/shrp
              git config --global user.name $USER
              git config --global user.email $EMAIL
              repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0
              repo sync --force-sync -j6 -c
       
       - name: Get SHRP Tree
         run: |
              mkdir device/GM
              cd device/GM
              git clone $TREE
              mv GM8_sprout_shrp GM8_sprout

       - name: Build SHRP
         run: |
              cd /home/runner/work/recovery-builder/recovery-builder/shrp/
              . build/envsetup.sh
              lunch omni_GM8_sprout-eng
              mka recoveryimage -j6

       - name: Upload On Web
         run: |
              cd /home/runner/work/recovery-builder/recovery-builder/shrp/out/product/
              ls
              wget https://raw.githubusercontent.com/Mikubill/transfer/master/install.sh
              chmod +x install.sh
              ./install.sh
              cd /home/runner/work/recovery-builder/recovery-builder/shrp/
              git clone $TREE
              mv GM8_sprout_shrp GM8_sprout
       
